version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.10

    working_directory: ~/repo

    steps:
      # Paso 1: Limpiamos el entorno virtual y el caché
      - run:
          name: Remove existing venv and clear pip cache
          command: |
            rm -rf venv
            pip cache purge

      # Paso 2: Obtenemos el código fuente
      - checkout

      # Paso 3: Creamos y activamos el entorno virtual, instalamos dependencias
      - run:
          name: Create and activate venv, install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      # Paso 4: Aseguramos la última versión de pytest y py
      - run:
          name: Install latest pytest and py
          command: |
            source venv/bin/activate
            pip install --upgrade pytest py

      # Paso 5: Ejecutamos linters y pruebas
      - run:
          name: Run flake8 and pytest
          command: |
            source venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v
