version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.10

    working_directory: ~/repo

    steps:
      # Step 1: Obtenemos el código fuente
      - checkout

      # Step 2: Limpiamos el entorno virtual y creamos uno nuevo
      - run:
          name: Remove existing venv
          command: rm -rf venv

      - run:
          name: Create and activate venv, install dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      # Step 3: Actualizamos pytest y py para evitar problemas de compatibilidad
      - run:
          name: Install latest pytest and py
          command: |
            source venv/bin/activate
            pip install --upgrade pytest py

      # Step 4: Ejecutamos linters y pruebas
      - run:
          name: Run flake8 and pytest
          command: |
            source venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v

      # Step 5: Docker build and push (opcional, descomenta si es necesario)
#      - setup_remote_docker:
#          docker_layer_caching: true
#      - run:
#          name: Build and Push Docker
#          command: |
#            source venv/bin/activate
#            docker build -t poc/$IMAGE_NAME:$TAG .
#            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
#            docker push ideaslocas/$IMAGE_NAME:$TAG
